### ISSUE TITLE
Link Decoration restriction and impact on reporting of impression metadata

### ISSUE THREAD

**Issue by captify-mgruau** [prebid/identity-gatekeeper#2]
Hello,

Quick question on PARRROT and this particular part about avoiding data leakage:

> In order to ensure that interest group info is not leaked in cases where the contextual ad wins, only the exact url provided to the fenced frame in one of the competing bid objects can be used to render the ad. This will prevent the interest group from being appended via link decoration to the contextual creative url.
> Likewise, to prevent leakage of contextual info in cases where the interest group wins, only the exact url returned from the DoveKey store can be used to render the ad.

TURTLEDOVE (and, as far as I understand, Dovekey and Sparrow too) were still allowing to pass impression metadata in the ad through the [conversion measurement API](https://github.com/WICG/conversion-measurement-api):
> <a conversiondestination="[eTLD+1]" impressiondata="[string]" impressionexpiry=[unsigned long long] reportingorigin="[origin]">

In this proposal, would the impressiondata field be kept to the discretion of the publisher?

**Comment by brodrigu** [comment]
In short, we don't think PARRROT needs to be any more restrictive than TURTLEDOVE. 

In TURTLEDOVE, the fenced frame is created by the browser using urls/web bundles provided in either the contextual or interest group ads, the ssp and dsp js does not have access to modify them.

In PARRROT, the fenced frame would be created by publisher controlled JS. In order to prevent this JS from communicating additional information via link decoration, the browser would perform some validation on the url.

In both proposals the creative rendered is generated by advertiser/dsp/ssp using whatever data they have available at generation time. Both the contextual and interest group creatives should be able to leverage the conversion measurement API. We can update the proposal to explicitly state that the final fenced frame would include `allow="conversion-measurement ‘src’)"`.

**Comment by captify-mgruau** [comment]
Thank you for confirming.
